# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180827_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='date_add',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watches',
            name='fashion',
            field=models.BooleanField(default=False),
        ),
    ]
