# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180828_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('summ', models.FloatField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='watches',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
