# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180914_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Men'), (1, 'Women'), (2, 'Unisex')], null=True),
        ),
    ]
