# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180914_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='made_by',
            field=models.IntegerField(choices=[(0, 'Swiss'), (1, 'Europe'), (2, 'Japan')], null=True),
        ),
    ]
