# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180915_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
