# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_watches_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='slug',
            field=models.SlugField(default=True, help_text='URL like line', max_length=255, unique=True, verbose_name='URL like str'),
        ),
    ]
