# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_brands'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='BrandName',
        ),
    ]
