# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180915_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameBrand',
        ),
    ]
