# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_namebrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watches',
            name='namebrand_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.NameBrand'),
        ),
    ]
