# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_watches_namebrand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='namebrand',
            name='slug',
            field=models.SlugField(default=True),
        ),
    ]
