# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_namebrand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='namebrand_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.NameBrand'),
        ),
    ]
