# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_watches_namebrand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namebrand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='namebrand',
            name='slug',
            field=models.SlugField(default=True, unique=True),
        ),
        migrations.AlterField(
            model_name='watches',
            name='slug',
            field=models.SlugField(default=True, unique=True),
        ),
    ]
