# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_namebrand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='discount',
            field=models.FloatField(default=False),
        ),
    ]
