# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20180920_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
