# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_watches_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namebrand',
            name='image',
            field=models.ImageField(default=False, upload_to='img'),
        ),
    ]
