# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180920_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='korpus',
            field=models.IntegerField(choices=[(0, 'Алюминий'), (1, 'Золото'), (2, 'Керамика'), (3, 'Керамика+сталь'), (4, 'Металл'), (5, 'Металл+позолота'), (6, 'Металл-полимер')], null=True),
        ),
        migrations.AddField(
            model_name='watches',
            name='mechanism',
            field=models.IntegerField(choices=[(0, 'Кварцевый'), (1, 'Механический'), (2, 'Механический с автоподзаводом'), (3, 'Автокварцевый'), (4, 'Кварцевый + механический с автоподзаводом')], null=True),
        ),
        migrations.AlterField(
            model_name='watches',
            name='made_by',
            field=models.IntegerField(choices=[(0, 'Швейцарские'), (1, 'Европейские'), (2, 'Японские')], null=True),
        ),
    ]
