# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180922_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='watches',
            old_name='namebrand_id',
            new_name='namebrand',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='summ',
        ),
        migrations.AddField(
            model_name='orders',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed at'),
        ),
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Opened at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderposition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.Orders'),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='watches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Watches'),
        ),
    ]
