# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20180923_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
