# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20180924_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watches',
            name='price',
        ),
    ]
