# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_watches_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
