# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180928_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watches',
            old_name='image',
            new_name='image_main',
        ),
        migrations.AddField(
            model_name='watches',
            name='image_one',
            field=models.ImageField(default=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='watches',
            name='image_three',
            field=models.ImageField(default=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='watches',
            name='image_two',
            field=models.ImageField(default=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Men'), (1, 'Women'), (2, 'Unisex')], max_length=1, null=True),
        ),
    ]
